/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LevelsLevelIdRouteImport } from './routes/levels.$levelId'
import { Route as LevelsLevelIdLessonSlugRouteImport } from './routes/levels.$levelId.$lessonSlug'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelsLevelIdRoute = LevelsLevelIdRouteImport.update({
  id: '/levels/$levelId',
  path: '/levels/$levelId',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelsLevelIdLessonSlugRoute = LevelsLevelIdLessonSlugRouteImport.update({
  id: '/$lessonSlug',
  path: '/$lessonSlug',
  getParentRoute: () => LevelsLevelIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/levels/$levelId': typeof LevelsLevelIdRouteWithChildren
  '/levels/$levelId/$lessonSlug': typeof LevelsLevelIdLessonSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/levels/$levelId': typeof LevelsLevelIdRouteWithChildren
  '/levels/$levelId/$lessonSlug': typeof LevelsLevelIdLessonSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/levels/$levelId': typeof LevelsLevelIdRouteWithChildren
  '/levels/$levelId/$lessonSlug': typeof LevelsLevelIdLessonSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/levels/$levelId'
    | '/levels/$levelId/$lessonSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/levels/$levelId'
    | '/levels/$levelId/$lessonSlug'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/levels/$levelId'
    | '/levels/$levelId/$lessonSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  LevelsLevelIdRoute: typeof LevelsLevelIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levels/$levelId': {
      id: '/levels/$levelId'
      path: '/levels/$levelId'
      fullPath: '/levels/$levelId'
      preLoaderRoute: typeof LevelsLevelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levels/$levelId/$lessonSlug': {
      id: '/levels/$levelId/$lessonSlug'
      path: '/$lessonSlug'
      fullPath: '/levels/$levelId/$lessonSlug'
      preLoaderRoute: typeof LevelsLevelIdLessonSlugRouteImport
      parentRoute: typeof LevelsLevelIdRoute
    }
  }
}

interface LevelsLevelIdRouteChildren {
  LevelsLevelIdLessonSlugRoute: typeof LevelsLevelIdLessonSlugRoute
}

const LevelsLevelIdRouteChildren: LevelsLevelIdRouteChildren = {
  LevelsLevelIdLessonSlugRoute: LevelsLevelIdLessonSlugRoute,
}

const LevelsLevelIdRouteWithChildren = LevelsLevelIdRoute._addFileChildren(
  LevelsLevelIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  LevelsLevelIdRoute: LevelsLevelIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
